### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by lewisdonovan** [stereobooster/react-snap#148]
Getting the following error when running react-snap:

```
---- snip ----
ðŸ”¥  /journal/page/2 Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
ðŸš§  skipping (19/22) /videos/page/1
?[91m(node:90) UnhandledPromiseRejectionWarning: Error: kill ESRCH
    at process.kill (internal/process.js:173:20)
    at killChrome (/app/node_modules/puppeteer/lib/Launcher.js:122:19)
    at Browser.close (/app/node_modules/puppeteer/lib/Browser.js:61:31)
    at /app/node_modules/react-snap/src/puppeteer_utils.js:209:21
    at /app/node_modules/highland/lib/index.js:1894:13
    at /app/node_modules/highland/lib/index.js:1576:9
    at Stream.s._send (/app/node_modules/highland/lib/index.js:1532:9)
    at Stream.write (/app/node_modules/highland/lib/index.js:1633:18)
    at Stream._send (/app/node_modules/highland/lib/index.js:959:26)
    at push (/app/node_modules/highland/lib/index.js:1498:19)
(node:90) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:90) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
---- snip ----
```

Below is my react-snap config in package.json:

```
  "reactSnap": {
    "puppeteerArgs": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-gpu"
    ],
    "puppeteerExecutablePath": "/usr/bin/chromium-browser",
    "inlineCss": false
  }
```

Using v1.10.0 of react-snap. Any help appreciated. Cheers.

**Comment by stereobooster** [comment]
Can happen that this is issue in puppeteer try to search in their issue tracker

**Comment by stereobooster** [comment]
It can happen that you are using wrong version of Chromium. See this issue https://github.com/GoogleChrome/puppeteer/issues/894

**Comment by lewisdonovan** [comment]
The issue was caused my shared memory running out during the execution of react-snap. My local build doesn't lag, so I'm not sure why it's happening on the server, but increasing the shared memory in the Docker container to 256m solved the problem.

Here's my Dockerfile:

```
FROM node:9-alpine as builder

# Installs latest Chromium (63) package.
RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@edge \
      nss@edge

COPY . /app

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Puppeteer v0.11.0 works with Chromium 63.
RUN yarn add puppeteer@0.11.0

# Add user so we don't need --no-sandbox.
RUN addgroup -S pptruser && adduser -S -g pptruser pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /app

# Run everything after as non-privileged user.
USER pptruser

RUN cd /app && yarn install && yarn run build

FROM nginx:mainline-alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/conf.d/main.conf
```

It's using Chromium 63 and Puppeteer 0.11.0.

**Comment by lewisdonovan** [comment]
This was actually related to an issue with yarn in the docker-node image I was using, more info here: https://github.com/nodejs/docker-node/issues/649 

If anyone has the same issue, you can either wait for the PR for the above issue to be merged in docker-node, or you can change:

```
FROM node:9-alpine as builder
```
to
```
FROM node:9.7-alpine as builder
```
In your Dockerfile
