### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by MEmmanuel** [stereobooster/react-snap#149]
Hello,

I'm trying to use react-snap, but I get this error immediatly:
```
> test@0.1.0 postbuild path/test
> react-snap

path/node_modules/react-snap/run.js:9
  ...reactSnap
  ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```
I just started this test project to see if I can reproduce the error, and I can..

Can someone please help me ?

**Comment by stereobooster** [comment]
Wrong version of node.js. Use 8.6+

**Comment by MEmmanuel** [comment]
Great ! Thx ! Stupid error..
