### ISSUE TITLE
Error when building : SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by ldevalbray** [stereobooster/react-snap#159]
Hello, thanks for this tool !

My issue : 
-----
I added the "postbuild":"react-snap" correctly in package.json.

When trying to build my app (built with [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate)) with react-snap : I get this error : 

```
> scotland2018@1.0.0 postbuild /home/louis/scotland2018
> react-snap

/home/louis/scotland2018/node_modules/react-snap/run.js:9
  ...reactSnap
  ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

```

Would you know why ?

**Comment by stereobooster** [comment]
You need node 8.6+

**Comment by ldevalbray** [comment]
Thank you for your quick answer ! 
I have a new error now ... I am sorry I am unfamiliar with those errors :s 
```

🔥  / pageerror: Error: Error: Minified React error #39; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=39&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (http://localhost:45678/main.03995167b31311de08f7.js:20:1473)
    at Object._renderSubtreeIntoContainer (http://localhost:45678/main.03995167b31311de08f7.js:6:98804)
    at render (http://localhost:45678/main.03995167b31311de08f7.js:6:99622)
    at Object../app/app.js (http://localhost:45678/main.03995167b31311de08f7.js:1:38431)
    at t (http://localhost:45678/main.03995167b31311de08f7.js:1:101)
    at Object.0 (http://localhost:45678/main.03995167b31311de08f7.js:20:179777)
    at t (http://localhost:45678/main.03995167b31311de08f7.js:1:101)
    at ./app/app.js (http://localhost:45678/main.03995167b31311de08f7.js:1:1898)
    at http://localhost:45678/main.03995167b31311de08f7.js:1:1907
🕸  (1/1) /

```

Thanks again

**Comment by stereobooster** [comment]
This is error in your application code. You should be able to see it when you open your application in the browser.

**Comment by ldevalbray** [comment]
Ofc, my bad !
```

✏️  / log: JSHandle@error
🕸  (1/7) /
✏️  /presentation log: 
🕸  (2/8) /project
🕸  (3/8) /teams
⚠️  404 page title does not contain "404" string
🕸  (4/8) /404.html
🚧  skipping (5/8) /ca920535340fd37cbae476d78b23b915.pdf
🕸  (6/8) /presentation
🕸  (7/8) /charities
🕸  (8/8) /partners

```


I think it succeeded ? But there are some errors ? Are those important ? How could I debug it ?

**Comment by stereobooster** [comment]
there are no errors - this is just information log
🕸- crawled page
✏️- `console.log`
⚠️- warning, not critical
🚧 - page skipped from crawling. In this case it is skipped, because this is pdf file

**Comment by ldevalbray** [comment]
Awesome Thanks ! Maybe worth putting it somewhere in the doc ? (or I missed it ? )

**Comment by stereobooster** [comment]
Yes documentation is somewhat behind. I have couple tickets about documentation, but do not have time at the moment
