### ISSUE TITLE
events.js:183       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by heshamelmasry77** [stereobooster/react-snap#174]
Hey 

I am getting this error now suddenly:

``` events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::45678
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at startServer (/Users/hesham/Documents/GitHub/webb-hesh/react-ui/node_modules/react-snap/index.js:472:12)
    at run (/Users/hesham/Documents/GitHub/webb-hesh/react-ui/node_modules/react-snap/index.js:498:50)
    at Object.<anonymous> (/Users/hesham/Documents/GitHub/webb-hesh/react-ui/node_modules/react-snap/run.js:7:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ```

**Comment by stereobooster** [comment]
Previous run of `react-snap` didn't exited properly - there is zombie process in the memory. FInd it (using your OS specific tools) and kill it. 

I guess this case needs a better error message.
