### ISSUE TITLE
Fails at postbuild script

### ISSUE THREAD

**Issue by zachfejes** [stereobooster/react-snap#181]
Hey there, we're running into a bit of an issue switching over from react-snapshot to react-snap. We're moving over as suggested in: https://github.com/geelen/react-snapshot/issues/96

We're using create-react-app, react-router, and redux. We've created a postbuild script in our package.json, and "reactSnap" attribute.

However, we keep getting the following error whenever we build:
```
  ...reactSnap
  ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sc-frontend-client@0.1.0 postbuild: `react-snap`
npm ERR! Exit status 1
```

Any insight as to why this might be happening?

**Comment by stereobooster** [comment]
you node 8.0+ (I'm using it with 8.6)

**Comment by zachfejes** [comment]
@stereobooster you were absolutely right - that solved our first problem!

If you're up for it, would you mind helping us figure out something else that's going wrong? It's now attempting to build our routes, but it is throwing the following error on several of them, and then ignoring several others and we're not sure why. This is the output:

```

pageerror: Error: SyntaxError: Unexpected identifier
    at Page._handleException (.../node_modules/puppeteer/lib/Page.js:427:38)
    at CDPSession.Page.client.on.exception (.../node_modules/puppeteer/lib/Page.js:103:60)
    at emitOne (events.js:115:13)
    at CDPSession.emit (events.js:210:7)
    at CDPSession._onMessage (.../node_modules/puppeteer/lib/Connection.js:219:12)
    at Connection._onMessage (.../node_modules/puppeteer/lib/Connection.js:119:19)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (.../node_modules/ws/lib/WebSocket.js:141:47)
🔥  /404.html pageerror: Error: SyntaxError: Unexpected identifier
    at Page._handleException (.../node_modules/puppeteer/lib/Page.js:427:38)
    at CDPSession.Page.client.on.exception (.../node_modules/puppeteer/lib/Page.js:103:60)
    at emitOne (events.js:115:13)
    at CDPSession.emit (events.js:210:7)
    at CDPSession._onMessage (.../node_modules/puppeteer/lib/Connection.js:219:12)
    at Connection._onMessage (.../node_modules/puppeteer/lib/Connection.js:119:19)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (.../node_modules/ws/lib/WebSocket.js:141:47)
✏️  / log: You may test your Stripe.js integration over HTTP. However, live Stripe.js integrations must use HTTPS.
✏️  /404.html log: You may test your Stripe.js integration over HTTP. However, live Stripe.js integrations must use HTTPS.
🔥  / pageerror: Error: SyntaxError: Unexpected identifier
    at Page._handleException (.../node_modules/puppeteer/lib/Page.js:427:38)
    at CDPSession.Page.client.on.exception (.../node_modules/puppeteer/lib/Page.js:103:60)
    at emitOne (events.js:115:13)
    at CDPSession.emit (events.js:210:7)
    at CDPSession._onMessage (.../node_modules/puppeteer/lib/Connection.js:219:12)
    at Connection._onMessage (.../node_modules/puppeteer/lib/Connection.js:119:19)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (.../node_modules/ws/lib/WebSocket.js:141:47)
✏️   log: You may test your Stripe.js integration over HTTP. However, live Stripe.js integrations must use HTTPS.
✏️   log: Our embeddable contains third-party, open source software and/or libraries. To view them and their license terms, go to http://goto.zendesk.com/embeddable-legal-notices
✏️  /404.html log: Our embeddable contains third-party, open source software and/or libraries. To view them and their license terms, go to http://goto.zendesk.com/embeddable-legal-notices
✏️  / log: Our embeddable contains third-party, open source software and/or libraries. To view them and their license terms, go to http://goto.zendesk.com/embeddable-legal-notices
🚧  skipping (1/4) /features
🚧  skipping (2/13) /pricing
🚧  skipping (3/13) /account
🚧  skipping (4/13) /shop/customize-cart
🚧  skipping (5/13) /blog
🚧  skipping (7/13) /contact
🚧  skipping (8/13) /faq
🚧  skipping (9/13) /privacy
🚧  skipping (10/13) /terms
🕸  (11/13) /
🕸  (16/17) /404.html
(node:3866) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Runtime.callFunctionOn): Target closed.
(node:3866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled willterminate the Node.js process with a non-zero exit code.
🕸  (17/17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ...@0.1.0 build: `react-scripts build && react-snap && sw-precache --config=sw-precache-config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sc-frontend-client@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2018-05-25T16_54_11_756Z-debug.log

```

Any thoughts you could provide could help us out a lot!

**Comment by stereobooster** [comment]
`pageerror: Error: SyntaxError: Unexpected identifier` this error comes from your webpage, you should be able to find it if you open your page in a browser. As soon as you fix it you will be able to proceed.
