### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by FelixKuehl** [stereobooster/react-snap#204]
I am getting the following error outputted on build when using react-snap:

UnhandledPromiseRejectionWarning { Error: Protocol error (Runtime.callFunctionOn): Object reference chain is too long undefined
    at Promise (/Users/felixkuehl/Developer/jmm/landing-page/node_modules/puppeteer/lib/Connection.js:202:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/felixkuehl/Developer/jmm/landing-page/node_modules/puppeteer/lib/Connection.js:201:12)
    at JSHandle.jsonValue (/Users/felixkuehl/Developer/jmm/landing-page/node_modules/puppeteer/lib/ExecutionContext.js:193:43)
    at Promise.all.msg.args.map.x (/Users/felixkuehl/Developer/jmm/landing-page/node_modules/react-snap/src/puppeteer_utils.js:32:39)
    at Array.map (<anonymous>)
    at Page.page.on.msg (/Users/felixkuehl/Developer/jmm/landing-page/node_modules/react-snap/src/puppeteer_utils.js:32:28)
    at emitOne (events.js:116:13)
    at Page.emit (events.js:211:7)
    at Page._addConsoleMessage (/Users/felixkuehl/Developer/jmm/landing-page/node_modules/puppeteer/lib/Page.js:510:10)
  message: 'Protocol error (Runtime.callFunctionOn): Object reference chain is too long undefined' }

This Error is printed for every route. At the end of the output I am getting.

🚧  skipping (1/2) /route1
🚧  skipping (2/3) /route2
🚧  skipping (3/4) /route3
🚧  skipping (4/9) /route4
🚧  skipping (5/9) /route5
🚧  skipping (6/9) /route6
🚧  skipping (7/9) /route7
🚧  skipping (8/9) /route8
🕸  (9/9) /
error Command failed with exit code 1.

In my index.jsx I am simply rendering like this:

```js
if (rootElement.hasChildNodes()) {
 hydrate(
    <Provider store={store}>
      <ErrorBoundary>
        <Locale>
          <Router>
            <ScrollToTop>
              <Entry variant={variant} />
            </ScrollToTop>
          </Router>
        </Locale>
      </ErrorBoundary>
    </Provider>,
    rootElement
  )
} else {
  render(
    <Provider store={store}>
      <ErrorBoundary>
        <Locale>
          <Router>
            <ScrollToTop>
              <Entry variant={variant} />
            </ScrollToTop>
          </Router>
        </Locale>
      </ErrorBoundary>
    </Provider>,
    rootElement
  )
}
```

I can provide further snippets if needed. Any idea what might cause this issue? I could not find similar problems on the internet. My assumption would be, that this is related to puppeteer.

Thanks for the help!

**Comment by stereobooster** [comment]
I saw something similar caused by very long `console.log` output. If you want it to be investigated further please provide reproducible example.

**Comment by FelixKuehl** [comment]
Wow thanks, this actually was the issue. By setting ```js console.log = function() {}``and disabling redux logger it worked! However the console output was not horribly long so this should maybe get investigated?
