### ISSUE TITLE
I use this to webpack Multiple entry app from create-react-app tips me  `ReferenceError: webpackJsonp is not defined`

### ISSUE THREAD

**Issue by xulayen** [stereobooster/react-snap#250]
# I use this to webpack Multiple entry app from create-react-app tips me  `ReferenceError: webpackJsonp is not defined`

``` js

Error: Uncaught [ReferenceError: webpackJsonp is not defined]
    at reportException (E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:58:24)
    at processJavaScript (E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:130:7)
    at HTMLScriptElementImpl._eval (E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:65:7)
    at E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:31:22
    at Object.check (E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:89:11)
    at E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:108:12
    at wrappedEnqueued (E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:255:16)
    at Request.request [as _callback] (E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:203:9)
    at Request.self.callback (E:\工作\PMP\pmpsummary\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13) ReferenceError: webpackJsonp is not defined
    at http://localhost:2325/static/js/index.a5b4c900.js:1:1
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at Object.runInContext (vm.js:120:6)
    at processJavaScript (E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:128:10)
    at HTMLScriptElementImpl._eval (E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:65:7)
    at E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:31:22
    at Object.check (E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:89:11)
    at E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:108:12
    at wrappedEnqueued (E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:255:16)
    at Request.request [as _callback] (E:\工作\PMP\pmpsummary\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:203:9)
� 'render' from react-snapshot was never called. Did you replace the call to ReactDOM.render()?

```

``` js

  plugins: [

    // //2018年8月28日 16:48:56 xulayen添加
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks(module) {
        // any required modules inside node_modules are extracted to vendor
        return (
          module.resource &&
          /\.js$/.test(module.resource) &&
          module.resource.indexOf(
            path.join(__dirname, '../node_modules')
          ) === 0
        )
      }
    }),
]

```

``` js
import { render } from 'react-snapshot';//服务端渲染
import AdminIndex from './admin/index';

render(<AdminIndex />, document.getElementById('root'));

```

``` js

  "scripts": {
    "build": "node scripts/build.js  && react-snapshot",
  },

```

**Comment by stereobooster** [comment]
which version of react-scripts?

**Comment by stereobooster** [comment]
The issue caused by the way webpack inserts chinks in the generated document. react-snap contains workaround for CRA-way configured webpack, other setups may not work as expected. Also discussed here https://github.com/stereobooster/react-snap/pull/170

**Comment by stereobooster** [comment]
Also this ticket https://github.com/stereobooster/react-snap/issues/145
