### ISSUE TITLE
react-snap breaking with react-microlink

### ISSUE THREAD

**Issue by dottjt** [stereobooster/react-snap#287]
I'm currently using a library which (I believe) async gets data from a link. It produces this error when building. 

```
🔥  error at /exercises/japanese-noun-congjuations { TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/usr/src/app/client/node_modules/puppeteer/lib/FrameManager.js:1230:21)
  -- ASYNC --
    at Frame.<anonymous> (/usr/src/app/client/node_modules/puppeteer/lib/helper.js:144:27)
    at Page.goto (/usr/src/app/client/node_modules/puppeteer/lib/Page.js:579:49)
    at Page.<anonymous> (/usr/src/app/client/node_modules/puppeteer/lib/helper.js:145:23)
    at fetchPage (/usr/src/app/client/node_modules/react-snap/src/puppeteer_utils.js:207:22)
    at process.internalTickCallback (internal/process/next_tick.js:77:7) name: 'TimeoutError' }
/usr/src/app/client/node_modules/highland/lib/index.js:1492
            throw new Error('Cannot write to stream after nil');
```

```
import MicrolinkCard from 'react-microlink';

            <MicrolinkCard 
              key={index}
              url={resource.url} 
              target='_blank' 
            />
```

is the code that is being used. Given it's async, what can I do?

**Comment by stereobooster** [comment]
Isn't it the same as https://github.com/stereobooster/react-snap/issues/240? Can you provide simple demo of the bug?
