### ISSUE TITLE
snap execution error: TimeoutError: Timed out after 30000 ms while trying to connect to Chrome

### ISSUE THREAD

**Issue by vovkind** [stereobooster/react-snap#318]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

Unable to execute snap of my local project, getting timeout exeception:

> react-snap-timeout-reproduct@0.1.0 postbuild c:\Users\XYZ\react-snap-timeout-reproduct
> react-snap

{ TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r609904
    at Timeout.onTimeout (c:\Users\Vladimib\Desktop\react-snap-timeout-reproduct\node_modules\puppeteer\lib\Launcher.js:353:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) name: 'TimeoutError' }

**Reproducible demo**
Link to GitHub repository or codesandbox with a demo of the bug behavior.

https://github.com/vovkind/react-snap-timeout-reproduct

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

Should work and create HTML snap of the CRA page

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

OS: Windows 7 X64
suspecting that it is the same issue: https://github.com/GoogleChrome/puppeteer/issues/3186

**Comment by stereobooster** [comment]
I can't reproduce it on my machine. This seems to be related to OS. I guess you need to wait until GoogleChrome/puppeteer#3186 resolved. You also can use Docker to workaround.

**Comment by rohan-deshpande** [comment]
I'm also seeing a similar issue on MacOS Mojave 10.14.5

```
error at / TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
```

**Comment by BriantAnthony** [comment]
This issue occurs in production environments from my experience. I haven't found a fix for this yet either...

If you create an ubuntu ec2 instance on AWS you can reproduce the problem.

**Comment by famouspotatoes** [comment]
Was there any resolution to this issue?
