### ISSUE TITLE
Object couldn't be returned by value

### ISSUE THREAD

**Issue by lionlin** [stereobooster/react-snap#321]
**Getting the following error when running react-snap:**

```
 { Error: Protocol error (Runtime.callFunctionOn): Object couldn't be returned by value
    at Promise (/Users/malin/react/auxopg/node_modules/puppeteer/lib/Connection.js:186:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/malin/react/auxopg/node_modules/puppeteer/lib/Connection.js:185:12)
    at JSHandle.jsonValue (/Users/malin/react/auxopg/node_modules/puppeteer/lib/ExecutionContext.js:239:43)
    at JSHandle.<anonymous> (/Users/malin/react/auxopg/node_modules/puppeteer/lib/helper.js:145:23)
    at objectToJson (/Users/malin/react/auxopg/node_modules/react-snap/src/puppeteer_utils.js:12:43)
    at Array.map (<anonymous>)
    at Page.page.on.msg (/Users/malin/react/auxopg/node_modules/react-snap/src/puppeteer_utils.js:40:30)
    at Page.emit (events.js:182:13)
    at Page._addConsoleMessage (/Users/malin/react/auxopg/node_modules/puppeteer/lib/Page.js:578:10)
  -- ASYNC --
    at JSHandle.<anonymous> (/Users/malin/react/auxopg/node_modules/puppeteer/lib/helper.js:144:27)
    at objectToJson (/Users/malin/react/auxopg/node_modules/react-snap/src/puppeteer_utils.js:12:43)
    at Array.map (<anonymous>)
    at Page.page.on.msg (/Users/malin/react/auxopg/node_modules/react-snap/src/puppeteer_utils.js:40:30)
    at Page.emit (events.js:182:13)
    at Page._addConsoleMessage (/Users/malin/react/auxopg/node_modules/puppeteer/lib/Page.js:578:10)
    at Page._onConsoleAPI (/Users/malin/react/auxopg/node_modules/puppeteer/lib/Page.js:506:10)
    at CDPSession.Page.client.on.event (/Users/malin/react/auxopg/node_modules/puppeteer/lib/Page.js:133:57)
    at CDPSession.emit (events.js:182:13)
    at CDPSession._onMessage (/Users/malin/react/auxopg/node_modules/puppeteer/lib/Connection.js:216:12)
  message:
   "Protocol error (Runtime.callFunctionOn): Object couldn't be returned by value" }

```

**my index code below:**

```
const rootElement = document.getElementById("root");
  if (rootElement.hasChildNodes()) {
    hydrate(<Provider store={store}>
      <App history={history} />
    </Provider>, rootElement);
  } else {
    render(<Provider store={store}>
      <App history={history} />
    </Provider>, rootElement);
  }
```
I found error from here and wonder why there is no catch to handle error?
```

const enableLogging = opt => {
  const { page, options, route, onError, sourcemapStore } = opt;
  page.on("console", msg => {
    const text = msg.text();
    if (text === "JSHandle@object") {
      Promise.all(msg.args().map(objectToJson)).then(args =>
        console.log(`💬  console.log at ${route}:`, ...args)
      );
    } else if (text === "JSHandle@error") {
      Promise.all(msg.args().map(errorToString)).then(args =>
        console.log(`💬  console.log at ${route}:`, ...args)
      );
    } else {
      console.log(`️️️💬  console.log at ${route}:`, text);
    }
  });
```

What will cause this error?Any help appreciated!

**Comment by iDVB** [comment]
Any incite @lionlin ? 
We're seeing the same error.

**Comment by dpw1** [comment]
I'm also experiencing the very same issue. @lionlin @iDVB any updates?

**Comment by iDVB** [comment]
Sorry @dpw1 we've since switched over to GatsbyJS for our ReactJS base and it has pretenders in its core.

**Comment by tiwatson** [comment]
Fixed in my own code by making sure to always return a React.Fragment instead of null
