### ISSUE TITLE
Properly handle errors in minimalcss

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/react-snap#45]
Example:

```
🔥  /shell.html pageerror: Error: DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object]') is not a valid name.
    at createElement (../node_modules/preact/dist/preact.esm.js:183:0)
    at createNode (../node_modules/preact/dist/preact.esm.js:364:0)
    at idiff (../node_modules/preact/dist/preact.esm.js:306:0)
    at diff (../node_modules/preact/dist/preact.esm.js:949:0)
    at vnode (../node_modules/preact-compat/dist/preact-compat.es.js:149:0)
    at __WEBPACK_IMPORTED_MODULE_0_react__ (index.js:30:7)
    at call (../webpack/bootstrap 3d46b713f8f74ea5ecff:49:0)
    at __webpack_require__ (../static/js/main.6fe07f11.js:3020:17)
    at call (../webpack/bootstrap 3d46b713f8f74ea5ecff:49:0)
    at http://localhost:45678/static/js/main.6fe07f11.js:1:1387
(node:17059) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object]') is not a valid name.
    at p (http://localhost:45678/static/js/main.6fe07f11.js:1:54860)
    at g (http://localhost:45678/static/js/main.6fe07f11.js:1:56858)
    at b (http://localhost:45678/static/js/main.6fe07f11.js:1:56327)
    at L (http://localhost:45678/static/js/main.6fe07f11.js:1:61366)
    at a (http://localhost:45678/static/js/main.6fe07f11.js:1:2078)
    at Object.<anonymous> (http://localhost:45678/static/js/main.6fe07f11.js:1:50384)
    at e (http://localhost:45678/static/js/main.6fe07f11.js:1:101)
    at Object.<anonymous> (http://localhost:45678/static/js/main.6fe07f11.js:1:39516)
    at e (http://localhost:45678/static/js/main.6fe07f11.js:1:101)
    at http://localhost:45678/static/js/main.6fe07f11.js:1:1387
(node:17059) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
🕸  (1/1) /shell.html
error Command failed with exit code 1.
```

`🔥  /shell.html...` - this is page error handled by **react-snap**
`(node:17059) UnhandledPromiseRejectionWarning:..` this is the same error unhandled from **minimalcss**

Extracted from https://github.com/stereobooster/react-snap/issues/36

**Comment by stereobooster** [comment]
It is fixed in 1.11.0 as far as I can tell
