### ISSUE TITLE
Unable to build with react-snap on Bitbucket

### ISSUE THREAD

**Issue by NikhilPunwaney** [stereobooster/react-snap#476]
## Bug Report

Running a build on Bitbucket fails with: 
Error: Failed to launch chrome!
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    at onClose (/opt/atlassian/pipelines/agent/build/node_modules/react-snap/node_modules/puppeteer/lib/Launcher.js:348:14)
    at ChildProcess.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/react-snap/node_modules/puppeteer/lib/Launcher.js:339:64)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
error Command failed with exit code 1.

My pipeline commands:
- yarn install -focus
- apt-get install -y gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
- export BUILD_TIMESTAMP=$(date -Iseconds)
- yarn run build

I have added react-snap ^1.23.0 to devDependencies in package.json.

In the same package.json file, I have added the following config (I have tried every combination of including and excluding the various fields): 
"reactSnap": {
    "puppeteerArgs": [
      "--no-sandbox",
      "--disable-setuid-sandbox"
    ],
    "puppeteerExecutablePath": "/usr/bin/chromium-browser"
  }

**Comment by BalaRajendran** [comment]
Same Issues I'm also facing
