### ISSUE TITLE
UnhandledPromiseRejectionWarning Error: Execution context was destroyed, most likely because of a navigation. at rewriteError (\node_modules\react-snap\node_modules\puppeteer\lib\ExecutionContext.js:167:15)

### ISSUE THREAD

**Issue by hirenatwiley** [stereobooster/react-snap#498]
## Bug Report

**Current Behavior**
**Having react snap following version**
"react-snap": "^1.23.0"

**Added following configuration for build**
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "postbuild": "react-snap"
  },
  "reactSnap": {
    "include": [
      "/site-crawl-page/"
    ],
    "inlineCss": true,
    "preconnectThirdParty": true,
    "preloadImages": true,
    "asyncScriptTags": true,
    "puppeteer": {
      "timeout": 0
    },
    "puppeteerArgs": [
      "--no-sandbox",
      "--disable-setuid-sandbox"
    ]
  }

Now when i perform **npm run build** getting following error
âœ…  crawled 593 out of 618 (/blog/cfa/page/7/)
ðŸ”¥  UnhandledPromiseRejectionWarning Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\ExecutionContext.js:167:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext._evaluateInternal (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\ExecutionContext.js:120:56)
    at async ExecutionContext.evaluate (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\ExecutionContext.js:48:12)
    at async Page.<anonymous> (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\index.js:174:11)
  -- ASYNC --
    at ExecutionContext.<anonymous> (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\Page.js:833:43)
    at Page.<anonymous> (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\helper.js:112:23)
    at Page.<anonymous> (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\index.js:174:22)
    at Page.emit (events.js:327:22)
    at NetworkManager.<anonymous> (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\Page.js:111:69)
    at NetworkManager.emit (events.js:315:20)
    at NetworkManager._onResponseReceived (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\NetworkManager.js:272:10)
    at CDPSession.emit (events.js:315:20)
    at CDPSession._onMessage (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\Connection.js:200:12)
  -- ASYNC --
    at Page.<anonymous> (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.<anonymous> (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\index.js:174:22)
    at Page.emit (events.js:327:22)
    at NetworkManager.<anonymous> (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\Page.js:111:69)
    at NetworkManager.emit (events.js:315:20)
    at NetworkManager._onResponseReceived (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\NetworkManager.js:272:10)
    at CDPSession.emit (events.js:315:20)
    at CDPSession._onMessage (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\Connection.js:200:12)
    at Connection._onMessage (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\Connection.js:112:17)
    at WebSocket.<anonymous> (c:\jenkins\workspace\WEL_UAT_Jobs\WEL_Static_Build_React_Snap\node_modules\react-snap\node_modules\puppeteer\lib\WebSocketTransport.js:44:24)
âš ï¸�  warning: inlining CSS more than 20kb (30.01171875kb, critical)
âœ…  crawled 594 out of 618 (/cfa/why-wiley/makes-us-better/)

**Comment by pipaliyachirag** [comment]
same issue any solution?

**Comment by woskaangel** [comment]
I've run into the same problem. Did you find a solution?

**Comment by pipaliyachirag** [comment]
Nope steel looking for solution 😂

**Comment by pipaliyachirag** [comment]
Because client went it urgent what i have done is i added express middleware routes and when some one vist the route it will load the files from it.

**Comment by gprasanth24k** [comment]
Same issue, any solution!?

**Comment by woskaangel** [comment]
@gprasanth24k You can write an endpoint to convert in the "package.json" file.

**Comment by gprasanth24k** [comment]
you mean proxy?

I added proxy in package.json file

"proxy":"https://xxzzyy.com/" this way

but same error plz help me in this

**Comment by woskaangel** [comment]
This is my Snap Setting.
`"reactSnap": {
    "include": [
      "/",
    ],
    "inlineCss": true,
    "puppeteer": {
      "cache": false
    },
    "puppeteerArgs": [
      "--no-sandbox",
      "--disable-setuid-sandbox"
    ]
  }`

If there is no problem setting, check if 45678 port is occupied elsewhere! If the 45678 port is occupied elsewhere, try rebooting your laptop or changing the port at 'node_modules/react-snap/index.js' 17line.
