### ISSUE TITLE
fail to build  postbuild: `react-snap`

### ISSUE THREAD

**Issue by satyendrasingh8** [stereobooster/react-snap#517]
error at /flipkart-daily-trivia-quiz TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at D:\webserv4u\quizbeater\node_modules\puppeteer\lib\LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (D:\webserv4u\quizbeater\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (D:\webserv4u\quizbeater\node_modules\puppeteer\lib\Page.js:674:49)
    at Page.<anonymous> (D:\webserv4u\quizbeater\node_modules\puppeteer\lib\helper.js:112:23)
    at fetchPage (D:\webserv4u\quizbeater\node_modules\react-snap\src\puppeteer_utils.js:232:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quizbeater@0.1.0 postbuild: `react-snap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quizbeater@0.1.0 postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by codevjs** [comment]
some problem

**Comment by codevjs** [comment]
in file puppeteer_utils.js replace networkidle0 to networkidle2, its work for me

![image](https://user-images.githubusercontent.com/48341107/106452644-26f62d00-64c3-11eb-9177-dacd29b85911.png)

**Comment by raunakchopra** [comment]
were you able to solve it?

**Comment by ProUnebit** [comment]
Same error, can't assemble project...

**Comment by MoukimHF** [comment]
Same problem

**Comment by jay-pavasiya** [comment]
Same problem
"react-snap": "^1.23.0"
![image](https://user-images.githubusercontent.com/82635946/161913187-a7dbf92c-b3d1-464c-a259-e4500aeb3bd7.png)

**Comment by shyamcse09** [comment]
I am also having same problem, Please suggest
