### ISSUE TITLE
TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded

### ISSUE THREAD

**Issue by Lazy-C0der** [stereobooster/react-snap#541]
> client@0.1.0 postbuild D:\OfficiaL\blog\client
> react-snap

??  error at / TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at D:\OfficiaL\blog\client\node_modules\puppeteer\lib\LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (D:\OfficiaL\blog\client\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (D:\OfficiaL\blog\client\node_modules\puppeteer\lib\Page.js:674:49)
    at Page.<anonymous> (D:\OfficiaL\blog\client\node_modules\puppeteer\lib\helper.js:112:23)
    at fetchPage (D:\OfficiaL\blog\client\node_modules\react-snap\src\puppeteer_utils.js:232:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.1.0 postbuild: `react-snap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@0.1.0 postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2021-08-21T21_02_16_602Z-debug.log

this one is updated version still not working

**Comment by vishishttiwari** [comment]
Exactly the same problem. Any solution?

**Comment by sushmavoleti** [comment]
Sam problem. Ay solution? I'm using react-snap 1.23.0

**Comment by igorilyichyov** [comment]
Same problem. react-snap 1.23.0

**Comment by joshephan** [comment]
Same on react-snap 1.23.0

**Comment by dominiczy** [comment]
I was able to fix this by setting Puppeteer options to "waitUntil": "networkidle2"

**Comment by harrymelka** [comment]
@dominiczy worked for me !! thanks

**Comment by NateBaldwinDesign** [comment]
Same issue, none of the above methods worked for me.

**Comment by stistoyanov** [comment]
Just add puppeteer.timeout with a greater value wich works for you and also skipThirdPartyRequests in reactSnap:

"scripts": {
    ...
    "postbuild": "react-snap"
  },
  "reactSnap": {
    "skipThirdPartyRequests": true,
    "puppeteer": { "timeout": 90000 },
    "puppeteerArgs": ["--no-sandbox", "--disable-setuid-sandbox"]
  },

**Comment by diohsu-mrliving** [comment]
> <img alt="Screenshot 2022-03-09 at 18 03 15" width="589" src="https://user-images.githubusercontent.com/4755048/157492681-b971b357-8c56-4c6d-a8d5-db791e1942a9.png">
> 
> Go to LifecycleWatcher.js inside node modules, _createTimeoutPromise functions line 137 and just add
> 
> `return new Promise(() => {});`
> 
> With that you are removing the timeout.
> 
> it should work, it's going to take more time to do it but it's working.

It works to me.
thanks!

**Comment by loganknecht** [comment]
I am experiencing this issue as well, and the above solutions did not work.

**Comment by smuchara** [comment]
for future refrences hope y'all found a solution but on my end degraded to version @1.10.0

npm install react-snap@1.10.0 --save-dev

this what worked for me
