### ISSUE TITLE
pageerror at /: SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by aakashpgandhi** [stereobooster/react-snap#557]
pageerror at /: SyntaxError: Unexpected token '.'
    at Object../node_modules/usehooks-ts/dist/esm/useEventListener/useEventListener.js (http://localhost:45678/main.js:14103:1)
    at __webpack_require__ (http://localhost:45678/main.js:19980:42)
    at eval (webpack://frontend/./node_modules/usehooks-ts/dist/esm/useEventListener/index.js?:5:75)  
    at Module../node_modules/usehooks-ts/dist/esm/useEventListener/index.js (http://localhost:45678/main.js:14092:1)
    at __webpack_require__ (http://localhost:45678/main.js:19980:42)
    at eval (webpack://frontend/./node_modules/usehooks-ts/dist/esm/useClickAnyWhere/useClickAnyWhere.js?:5:75)
    at Module../node_modules/usehooks-ts/dist/esm/useClickAnyWhere/useClickAnyWhere.js (http://localhost:45678/main.js:13927:1)
    at __webpack_require__ (http://localhost:45678/main.js:19980:42)
    at eval (webpack://frontend/./node_modules/usehooks-ts/dist/esm/useClickAnyWhere/index.js?:5:75)  
✅  crawled 1 out of 1 (/)

i am getting this error while running npm run postbuild

**Comment by chrismadufor** [comment]
Hi @aakashpgandhi I am getting a similar error. Have you been able to resolve it?

**Comment by stefanoschrs** [comment]
Hey @aakashpgandhi @chrismadufor everything was working fine for me for the last year until today that I started getting this error, without any changes to the node version & packages 🤷🏽‍♂️ Did you find any solution?

**Comment by Silur** [comment]
same issue here with vite

**Comment by sbaptista18** [comment]
Hi!
Having this error in a React project on a Mac, but it runs just fine in another React project on a Windows. I already checked the dependencies, the code itself, syntax errors, and I found nothing.
Any insight on this?

Thanks!

**Comment by OmarAbdo** [comment]
I'm seeing `pageerror at /: SyntaxError: Unexpected token '?`' on my react project (With vite & typescript)

**Comment by dimonb** [comment]
same one

 react-snap

🔥  pageerror at /: SyntaxError: Unexpected token '?'

✅  crawled 1 out of 1 (/)

**Comment by ashu-dev-ops** [comment]
any solution

**Comment by JSpiner** [comment]
same here

**Comment by djiworks** [comment]
same for me using `vite v4.4.9` and `"react": "^18.2.0", "react-router-dom": "^6.16.0"`

**Comment by juandiegombr** [comment]
I had a similar error and I solved it with this configuration in the `package.json`:

```
  "reactSnap": {
    "source": "public"
  }
  ```

**Comment by djiworks** [comment]
Hi, on my side, the issue was not directly due to react-snap. I got `Unexpected token '?'`. Actually this error was a build output issue.

My potential explanation:
Vitejs using `tsc & vite build` was compiling in `es6`. So in output files in `dist` folder there was some lines of code containing `??` operator which was not handle by old browser (it was returning `Unexpected token '?'` because it just understand the normal `?` operator. [https://stackoverflow.com/questions/65396855/syntaxerror-unexpected-token](https://stackoverflow.com/questions/65396855/syntaxerror-unexpected-token)

However, as react snap is using puppeteer, I think the browser was not able to handle `es6`. So I try to update the version of puppeteer used by react-snap without success until I found how to force compilation to make output in old `es5` files.

I did this to make it work perfectly with vitejs : [https://github.com/vitejs/vite/discussions/10519](https://github.com/vitejs/vite/discussions/10519).

PS: I had to test my code on very old iPad using old safari version to be able to found the solution. Once it worked on the device, it was working also with pupeteer. I say this because depending on the error, maybe you can resolve it without changing compilation options and just change the JS notation used (I think about function declaration using `=>`).

PPS: to better found error source, use `await puppeteer.launch({ dumpio: true });` in react-snap source code for testing purpose. This will basically "pipe browser process stdout and stderr into process.stdout and process.stderr", which means it will redirect browser logs to whatever main process, server, etc. you are running.

**Comment by Earu** [comment]
Hi, I have the same issue, however it seems that on my side react-i18next is the responsible for this. It's very likely that it's using newer syntax that react-snap's puppeteer process does not like. Putting this here for anyone that might run into this.

**Comment by alex-chuev** [comment]
It look like you can specify `PUPPETEER_CHROMIUM_REVISION` variable in `.env.production` file with desired chromium version to support modern syntax.

**Comment by HakanSungur** [comment]
Same problem.

**Comment by dauhialar** [comment]
see https://github.com/stereobooster/react-snap/issues/577#issuecomment-2370022442 from #577 - hope it helps!

**Comment by oladelemi** [comment]
Solution above by @juandiegombr  solved it. 

EDIT: 
using reactsnap public like below only lets the homepage gets crawled and your subpages won't be available to Web Crawlers 
"reactSnap": {
    "source": "public"
  }

Updating Package.json browserslist like in  [this comment](https://github.com/stereobooster/react-snap/issues/577#issuecomment-2370022442) by @dauhialar fixed it for me

**Comment by SimoneMSR** [comment]
The solution [above](https://github.com/stereobooster/react-snap/issues/557#issuecomment-2706894717) did not fix the issue. 

I would like to debug the problem, but stack traces are empty. Could you help to debug?

Is this project still maintained?

My project uses Parcel. Here are my dev dependencies

```
"devDependencies": {
    "@types/react": "^19.1.3",
    "@types/react-dom": "^19.1.3",
    "parcel": "2.15.2",
    "react-snap": "^1.23.0",
    "typescript": "^5.8.3"
  },
```

**Comment by SimoneMSR** [comment]
I solved by replacing the following files from [@Amani007](https://github.com/amanix007/react-snap)
```
- package.json
- src/puppeteer_utils.js
```

After `npm install`, it works! 
I am aware that these sources are from a fork of the project. I will look for PR
