### ISSUE TITLE
pageerror: Error: SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by jidan70** [stereobooster/react-snap#59]
Hi, i always get this error, no matter how i change html or the `homepage` field in the package.json. Thank you in advance for your help

`🔥  / pageerror: Error: SyntaxError: Unexpected token <
    at Page._handleException (/Users/Chevalier/projects/lola-client-landing-react/node_modules/puppeteer/lib/Page.js:295:38)
    at Session.Page.client.on.exception (/Users/Chevalier/projects/lola-client-landing-react/node_modules/puppeteer/lib/Page.js:86:60)
    at emitOne (events.js:115:13)
    at Session.emit (events.js:210:7)
    at Session._onMessage (/Users/Chevalier/projects/lola-client-landing-react/node_modules/puppeteer/lib/Connection.js:199:12)
    at Connection._onMessage (/Users/Chevalier/projects/lola-client-landing-react/node_modules/puppeteer/lib/Connection.js:98:19)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (/Users/Chevalier/projects/lola-client-landing-react/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/Users/Chevalier/projects/lola-client-landing-react/node_modules/ws/lib/Receiver.js:389:14)
🕸  (1/1) /`

index.html

![html2](https://user-images.githubusercontent.com/10445121/33297361-d5bc2726-d3e0-11e7-90de-b1d1cb08e1a6.png)

package.json
![json](https://user-images.githubusercontent.com/10445121/33297449-555459f4-d3e1-11e7-9d04-72b1f0b06fc6.png)

**Comment by jidan70** [comment]
I modified the index.js of react-snap to just run the server and  i have this when i try to go on the main.css of my app, this is the index.html
![jsishtml](https://user-images.githubusercontent.com/10445121/33298692-077d4d24-d3e8-11e7-8474-22d7e68b9b45.png)

And now if i remove `landing-client` in the url i have the correct css file, where is `landing-client` set? because when i console.log `response` in `page.on("response", async response =>` i got this in the url requested

**Comment by jidan70** [comment]
so i have replaced the `homepage` field in package.json by "/landing-page" and it's good now :) i just forgot that my variable env PUBLIC_URL was set to "/landing-page" so the files requested in the index.html was to '/landing-page'.
