### ISSUE TITLE
react-snap exits with status code 1 but no reason why

### ISSUE THREAD

**Issue by jonathaningram** [stereobooster/react-snap#69]
Reproducible example at https://github.com/govau/cloud.gov.au/tree/master/www/ui

Run `yarn build && yarn build-2-TODO` and you'll see the command fails but with no reason why:

```
$ yarn build && yarn build-2-TODO
yarn run v1.3.2
$ react-scripts-ts build
Creating an optimized production build...
No valid rules have been specified
ts-loader: Using typescript@2.6.2 and /Users/Jonathan/go/src/github.com/govau/cloud.gov.au/www/ui/tsconfig.json
Compiled successfully.

File sizes after gzip:

  101 KB    build/static/js/0.1664397f.chunk.js
  73.24 KB  build/static/js/main.fb89c8e0.js
  1.2 KB    build/static/js/1.1f44138b.chunk.js
  291 B     build/static/js/3.c54b25e2.chunk.js
  288 B     build/static/js/2.a77791b7.chunk.js
  226 B     build/static/css/main.688a7215.css

The project was built assuming it is hosted at the server root.
To override this, specify the homepage in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

✨  Done in 18.99s.
yarn run v1.3.2
$ react-snap
🕸  (1/4) /
🕸  (2/4) /404.html
🕸  (3/4) /about/
🕸  (4/4) /insights/
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any ideas?

**Comment by stereobooster** [comment]
This is what I get

```
yarn build
...
yarn build-2-TODO
...
🕸  (1/4) /
🔥  /insights/ pageerror: Error: SyntaxError: Unexpected token < in JSON at position 0
    at http://localhost:45678/static/js/0.81dd690f.chunk.js:1:3016
    at call (../static/js/0.81dd690f.chunk.js:61:22)
    at step (../static/js/0.81dd690f.chunk.js:42:52)
    at call (../static/js/0.81dd690f.chunk.js:46:96)
    at step (../static/js/0.81dd690f.chunk.js:42:52)
    at next (../static/js/0.81dd690f.chunk.js:33:57)
    at <anonymous>
...
```

**Comment by jonathaningram** [comment]
@stereobooster thanks for your help. Interestingly I still cannot reproduce getting a stack trace out of this myself. Maybe it's my version of node compared to yours:

```
$ npm --version
5.5.1
$ node --version
v9.0.0
```

Either way, I appreciate your help and I'll look into it from my end to figure out how to make sure that the app doesn't crash when trying to crawl when that API call is being made.

**Comment by stereobooster** [comment]
> I still cannot reproduce getting a stack trace out of this myself

yes this is mystery. My versions

```
node -v
v8.6.0
npm -v
5.3.0
yarn -v
1.2.1
```

You can detect reactSnap like this `const snap = navigator.userAgent !== 'ReactSnap';`. And use something else instead of actual content, for example [react-content-loader](https://github.com/danilowoz/react-content-loader)
