### ISSUE TITLE
Error when building with create-react-app

### ISSUE THREAD

**Issue by AndasDev** [stereobooster/react-snap#8]
Hello,

I've cloned the example repository which was created with create-react-app: https://github.com/badsyntax/react-snap-example.
I installed react-snap using `npm install react-snap --save-dev`.
In the package.json, I also changed `"build": "react-scripts build"` to `"build": "react-scripts build && react-snap",`. In my command line I ran `npm run build`, and got the following error:

```
/Users/Ludo/Documents/sites/react/react-snap-example/node_modules/react-snap/index.js:45
    ...defaultOptions,
    ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-snap-example@0.1.0 build: `react-scripts build && node ./node_modules/react-snap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-snap-example@0.1.0 build script 'react-scripts build && node ./node_modules/react-snap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-snap-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts build && node ./node_modules/react-snap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-snap-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-snap-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Ludo/Documents/sites/react/react-snap-example/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "snap"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-snap-example@0.1.0 snap: `npm run build && node ./node_modules/react-snap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-snap-example@0.1.0 snap script 'npm run build && node ./node_modules/react-snap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-snap-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && node ./node_modules/react-snap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-snap-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-snap-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Ludo/Documents/sites/react/react-snap-example/npm-debug.log
```

when I changed `"build": "react-scripts build && react-snap"` to `"build": "react-scripts build && node ./node_modules/react-snap",` I got the same error, and when I ran `npm run snap` like in the tutorial aswell.

Am I doing something wrong?

Ludo

**Comment by stereobooster** [comment]
The example is outdated sorry for that. Just create an empty project with create-react-app and follow instructions from readme of `react-snap`. I will update example later.

**Comment by stereobooster** [comment]
i updated example take a look https://github.com/badsyntax/react-snap-example/pull/1

**Comment by stereobooster** [comment]
Actually problem is not in example, but with version of node.

It is strange it didn't complain about version, because react-snap specifies version as

```
  "engines": {
    "node": ">= 8.6.0"
  },
```

Theoretically it is possible to support node 6, but it requires transpilation step, which complicates development process. So I decided to use latest node.
